language: java

jdk:
  - openjdk8

# For clean gradle output
env:
  global:
    - TERM=dumb
    - secure: zD2OpXUJBfnZq7mJJLswJaZ3s1W+WN5y1bRs/DvWfIbRzpdr/j9C3uWjYTHnOUwpPPdCYkk6V/kvWmlFHcB+CA/14oDGC8o8ag3SCXd1T/WlU7W9aW8OvZy0oyBErss8pZHko6OQGNX70mlNd/fDqPp1GBsy4VLKjYoSJfLKZJ5AM3uZKFQzeqpXri7iCLeGn+S6+jaOXAipqSxDCopBmtS1fJkrpM+8QdpBqalP8FalX3vTdQDjBE3hGGrdyDHWXXprVDf8/qc9s/38ulZBYAjRhOoFSIk0vrFCz1IrBenYxFEaTGd9CfJWExBq0ViZFMad4VzkTojz+PE8aKVsJnnEYbifkG8bNBcNqdVHXae+5mKYc8FXBy2yYXlrk0mtmdf+KxKpbl06A9kotWmLm5BX9pz+mZrjITd4QkwP1Zv6WDakDEimQfwJ4q7LCe1norA3BK1KiQej6FQI1iFruCXl3xA/L6TzpQ0W/MY/ne7Smz8Tptq2T6JVXgSvUXW49BG5usG4SYVlg+2LukJBmP6+L21M1ujYQLEYBaM/1s77FC6sEwHDCzgexEo448ss52B8mPX8uFY0C5LKC3zGPGCbk5KxcJIrIswuQMaqt60bSYEDUuFC97waNr6aZWWce3sutqlSY6kJZRkv3AbLlq+FDL+A3Emh45EEY+/foAg=
    - secure: 3T6qK/e7IUDwGH1NjKXWbqmwxejNU0hltJ/QFsIwtJF/NCO9dj1ZmZi1GxfeIJjZEeuxdzg0HXUaO6IQWzeKbw7Fyid/WkOCHKXaoNr1+pA25JIidWbv691HgUYVYWffEMpND+anE1Ls5L5PxOXaRRJGfFUb19bcAj9lE98hRm2OMfAg31lxvi8aqGxKWVYhCMlW3ERDzB7/mwI0uHcX8JOcGeS4ysSTlR4tF0bRWWulanv59ltgQMbfs6X/a4PP5igVi8yExwLtFL2MZ/5Q38TEyj29kLoVQQW0oavCvzKa7GeB12LJ8vWJQqwCICYY46qMYGHc98aVjZ4c/pHqxsDivLr096J9qXU+wMRtRlPFk/x7eG7lMT1zuEqZF5gXLTpgVFU2yXH735h+hnMGdaywUAzgVRgG544VCf6AwE8udyxWMXkz/0h+LuFck1l9TE1RC4l7PrfxxqV9AG6u1Fy3oHfPkWrGd7AvVOyOGH4I4gK7hg9rTgl3GdsNYyEoVAk6x2qOIj8+zdluXYJ4qw8bhS2Fe/5E951/vOV9m+Jb+vJV41QOkhguNam2UvkfGvrKAsqpYyBS1twZd3+NFSV+2s+rbNd4Rx45kBbfo3O//CsZAnhhK50Kn//ddLUTEWZjMy4I0tyMXIHvisXPd47JsNCQCeBhxVGZpP9MeEs=

# These files change at every build, and should not be cached
# https://docs.travis-ci.com/user/languages/java/#Caching
before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

# Cache Gradle's dependencies and wrapper download
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

deploy:
  - provider: script
    script: ./gradlew publishPlugins -Pgradle.publish.key=$GRADLE_API_KEY -Pgradle.publish.secret=$GRADLE_API_SECRET
    on:
      tags: true
